### ISSUE TITLE
Is there a pre-commit job that does the opposite of this tool?

### ISSUE THREAD

**Issue by cclauss** [asottile/flake8-walrus#68]
The walrus operator can be quite helpful but it is not yet widely adopted.  All the [walrus-related packages on PyPI](https://pypi.org/search/?q=walrus) are either unrelated to `:=` or they actively **_discourage_** its use.  It would be cool to have a pre-commit tool that would spot where `:=` could be used and make the conversion.  This could accelerate the broader adoption of `:=` on Python 3.8+ codebases.

**Comment by nuztalgia** [comment]
@cclauss There is now: https://github.com/MarcoGorelli/auto-walrus#usage-as-a-pre-commit-hook 😜
